name: Pipeline - Laboratorio Final

on:
  push:
    branches:
      - feat-movie

jobs:
  sonarcloud_analysis:
    name: SAST
    runs-on: ubuntu-latest
    env:
      APP_PATH: 'src'
      
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install sonar-scanner-cli

      - name: 2. Análisis SAST con SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=aacontre\
            -Dsonar.organization=aacontreGithub \
            -Dsonar.sources=${{ env.APP_PATH }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.sourceEncoding=UTF-8