name: Pipeline - Laboratorio Final

on:
  push:
    branches:
      - feat-movie

jobs:
  clone-repository:
    name: Clonar repositorio y preparar entorno
    runs-on: ubuntu-latest
    
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: laboratorio-final
      SONAR_ORG: olimpo 


    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
        path: src      

    
    - name: Verify repository structure
      run: |
        echo "Repositorio clonado:"
        ls -la src/
        echo ""
        echo "Estructura de directorios:"
        tree -L 2 src/
        
   
    - name: Set up environment
      run: |
        echo "Entorno de trabajo..."
        cd src
        echo "Ruta actual: $(pwd)"
        echo "Versión de Python: $(python --version || echo 'Python no encontrado')"
        echo "Versión de Docker: $(docker --version || echo 'Docker no encontrado')"


    - name: Setup SonarCloud project
      id: sonar-setup
      run: |
        .github/scripts/inicioSonarcloud.sh \
        "${{ secrets.SONAR_TOKEN }}" \
        "${{ github.event.repository.name }}" \
        "olimpo"          

    - name: Use project status
      if: steps.sonar-setup.outputs.proyectoExiste == '0'
      run: echo "Proyecto nuevo creado"

        